export const episodes = [
  {
    id: 1,
    title: "The Real Talk On Men's Sexual Health",
    date: "April 2, 2024",
    image: "/podcast/podcast-sexual-health.png",
    duration: "15:39",
    category: "Sexual Health",
    author: "James Nicole",
  },
  {
    id: 2,
    title: "The Hair Regrowth Journey: Real Talk With Experts",
    date: "April 2, 2024",
    image: "/podcast/podcast-hair-regrowth.png",
    duration: "25:40",
    category: "Hair Loss",
    author: "James Nicole",
  },
  {
    id: 3,
    title: "Breaking The Silence: Men's Mental Health Awareness",
    date: "March 15, 2024",
    image: "/podcast/podcast-mental-health.png",
    duration: "51:20",
    category: "Mental Health",
    author: "Arthur Brown",
  },
  {
    id: 4,
    title: "Healthy Eating For Men: Meal Plans That Work",
    date: "March 5, 2024",
    image: "/podcast/podcast-healthy-eating.png",
    duration: "47:33",
    category: "Nutrition",
    author: "James Nicole",
  },
  {
    id: 5,
    title: "Fitness After 40: Maintaining Strength and Mobility",
    date: "February 20, 2024",
    image: "/podcast/podcast-hair-regrowth.png",
    duration: "38:15",
    category: "Fitness",
    author: "Arthur Brown",
  },
  {
    id: 6,
    title: "Sleep Optimization for Better Health",
    date: "February 10, 2024",
    image: "/podcast/podcast-hair-regrowth.png",
    duration: "42:18",
    category: "Wellness",
    author: "James Nicole",
  },
  {
    id: 7,
    title: "Stress Management Techniques for Modern Men",
    date: "January 25, 2024",
    image: "/podcast/podcast-hair-regrowth.png",
    duration: "36:45",
    category: "Mental Health",
    author: "Arthur Brown",
  },
  {
    id: 8,
    title: "Preventative Health Screenings Every Man Should Know",
    date: "January 12, 2024",
    image: "/podcast/podcast-hair-regrowth.png",
    duration: "49:22",
    category: "Preventative Care",
    author: "James Nicole",
  },
  {
    id: 9,
    title: "Preventative Health Screenings Every Man Should Know",
    date: "January 12, 2024",
    image: "/podcast/podcast-hair-regrowth.png",
    duration: "49:22",
    category: "Life style",
    author: "James Nicole",
  },
];
